import json
from json import JSONDecodeError
from pydantic import BaseModel, Field, field_validator


class AgentOutput(BaseModel):
    notes: list[dict] = Field(
        ...,
        description="A list of note events generated by the AI agent, each represented as a dictionary compatible with Tone.js library.",
    )

    @field_validator("notes", mode="before")
    @classmethod
    def parse_notes(cls, value):
        """
        Accept a raw JSON string or a list for notes and normalize to list[dict].
        """
        if value is None:
            raise ValueError("notes are required")
        if isinstance(value, str):
            try:
                value = json.loads(value)
            except JSONDecodeError as exc:
                raise ValueError(f"notes must be JSON array or list: {exc}") from exc
        if not isinstance(value, list):
            raise ValueError("notes must be a list or JSON string representing a list")
        if not all(isinstance(item, dict) for item in value):
            raise ValueError("each note entry must be a dictionary")
        return value
